  
name: Build Android by AyiAngio
on:
  push:
    branches:
      - master
jobs:

  build-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Create ENV
        run: |
          cp .env.prod .env 
      - name: Install npm dependencies
        run: |
          npm install
      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew
      - name: Build Android Release
        env: 
          GOOGLE_API: ${{ secrets.GOOGLE_API }}
          WEB_CLIENT: ${{ secrets.WEB_CLIENT }}
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ayiangio.apk
          path: android/app/build/outputs/apk/release/