  
name: Build Android and iOS
on:
  push:
    branches:
      - master
jobs:
  # install-and-test:
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - uses: actions/checkout@v2
  #     - name: Install npm dependencies
  #       run: |
  #         npm install

  build-android:
    # needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: testing.apk
          path: android/app/build/outputs/apk/release/